set(CTEST_PROJECT_NAME "openloco")
set(CTEST_NIGHTLY_START_TIME "01:00:00 CET")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "cdash.brandstifter.local:8008")
set(CTEST_DROP_LOCATION "/submit.php?project=openloco")
set(CTEST_DROP_SITE_CDASH TRUE)